### ISSUE TITLE
Possible Bug: After retries have been exhausted and no default value an exception-info other than the original is thrown

### ISSUE THREAD

**Issue by DarrenBishop** [BrunoBonacci/safely#5] opened 2020-08-11 15:30 UTC
### Scenario:

The processing logic for a `compojure-api` route needs to perform an external check (http client call) before returning `OK 200`.

The external check can fail; it's desirable to be retried, according to some policy.

Retry or not, handling of the exception from the failed external check is deferred to a `compojure-api` exception-handler, which constructs an appropriate response i.e. not `OK 200`, possibly `FORBIDDEN` or `BAD REQUEST`.

### Observations:

With retry configured, the exception that propagates to the `compojure-api` exception-handler is not the exception that the external check throws and thus is not handled correctly (at all); it manifests as a `500` error which is misleading.

With no retries i.e. `:retryable?` function yields `falsey`, the original exception from the external check is propagated

### Initial Thoughts:

Use of `safely` or any attempts to retry an internal operation should not leak to the `compojure-api` exception-handler; this would be necessary if deciding to handle `safely`'s exception.

### Proposed Change:
The original exception be propagated in all scenarios?

### Enhancement:
If knowledge of retries having taken place must be available for context, is it possible to add those details in a suppressed exception?

**Comment by BrunoBonacci** [comment] 2020-08-11 18:29
Thanks Darren for reporting this. 
I will look into it as soon as I’m back from my holidays. 
In the meantime would it be possible to get a code example of the issue?

Regards 
Bruno

**Comment by BrunoBonacci** [comment] 2020-08-25 16:20
Hi @DarrenBishop,

do you have a code example that illustrates the problem above?

**Comment by BrunoBonacci** [comment] 2020-08-26 19:11
Hi @DarrenBishop,

the original exception is always available as the `cause` of the ex-info exception.

```
(safely
      (/ 1 0)
      :on-error
      :log-stacktrace false
      :max-retries 3)
```

will produce the following exception-stacktrace
```
clojure.lang.ExceptionInfo: Trapped expected error during safe block execution. {:queue-size 5, :half-open-strategy :linear-ramp-up, :tracking-capture nil, :circuit-breaker-strategy :failure-threshold, :log-level :warn, :tracking-tags nil, :default :safely.core/undefined, :counters-buckets 10, :retryable-error? nil, :sample-size 100, :thread-pool-size 10, :grace-period 3000, :failure-threshold 0.5, :track-as "scratch[l:131, c:5]", :ramp-up-period 5000, :tracking :enabled, :log-errors true, :log-stacktrace false, :max-retries 3, :call-site "scratch[l:131, c:5]", :log-ns #namespace[scratch], :cancel-on-timeout :always, :timeout 9223372036854775807, :failed? #function[clojure.core/constantly/fn--4614], :attempt 3, :retry-delay [:random-exp-backoff :base 300 :+/- 0.5 :max 60000], :message "Trapped expected error during safe block execution."}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at safely.core$safely_fn$fn__15457.invoke(core.clj:661)
	at safely.core$safely_fn.invokeStatic(core.clj:638)
	at safely.core$safely_fn.doInvoke(core.clj:399)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at scratch$eval18720.invokeStatic(form-init354238636275204869.clj:131)
	at scratch$eval18720.invoke(form-init354238636275204869.clj:130)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6890)
	at clojure.core$eval.invokeStatic(core.clj:3105)
	at clojure.core$eval.invoke(core.clj:3101)
	at nrepl.middleware.interruptible_eval$evaluate$fn__762.invoke(interruptible_eval.clj:91)
	at clojure.main$repl$read_eval_print__7408$fn__7411.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7408.invoke(main.clj:240)
	at clojure.main$repl$fn__7417.invoke(main.clj:258)
	at clojure.main$repl.invokeStatic(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:174)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__788$fn__792.invoke(interruptible_eval.clj:155)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__889$fn__891.invoke(session.clj:190)
	at nrepl.middleware.session$session_exec$main_loop__889.invoke(session.clj:189)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:832)

Caused by: java.lang.ArithmeticException: Divide by zero
	at clojure.lang.Numbers.divide(Numbers.java:158)
	at clojure.lang.Numbers.divide(Numbers.java:3808)
	at scratch$eval18720$fn__18721.invoke(form-init354238636275204869.clj:132)
	at safely.core$make_attempt_direct.invokeStatic(core.clj:257)
	at safely.core$make_attempt_direct.invoke(core.clj:253)
	at safely.core$make_attempt.invokeStatic(core.clj:388)
	at safely.core$make_attempt.invoke(core.clj:382)
	at safely.core$safely_fn$fn__15457.invoke(core.clj:640)
	... 24 more
```

Exception are wrapped to provide uniformity between all different cases (circuit-breaker errors timeout, queue-full, circuit-open) and execution errors like ArithmeticException in this case. Additionally, there is important information associated with the ex-info error with the details of the state of the retry loop/conditions.

You can always retrieve the original exception with `(ex-cause x)`

**Comment by DarrenBishop** [comment] 2020-08-27 20:01
Sorry @BrunoBonacci, I didn't catch your reply (Olivier just poked me).

I will try to produce something for you.

However, it sounds like this is a feature. Just seems undesirable if you have a custom handler somewhere for exception `A` that will not be invoked if an external config change determines some operation becomes subject to retries resulting in exception `B` being propagated.

Meanwhile, I actually hacked on Safely: suppressed-safely that wraps safely, attaches safely's exception as a suppressed exception on the triggering exception.

Incidentally, also got those retry-tags working.

**Comment by BrunoBonacci** [comment] 2020-09-05 14:21
Hi Darren,

Since it looks like this was expected behaviour,
I will close this issue.
If there is anything else, feel free to reopen it.

Bruno

**Closed as completed** 2020-09-05 14:25 UTC
Labels: wontfix
